version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: product_catalog_postgres
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: alexSecret
      POSTGRES_DB: productCatalogService
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alex -d productCatalogService"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: